```{r}
library(ggplot2)
library(patchwork)
library(stringr)
library(tidyverse)
library(dplyr)
library(cowplot)
library(digest)
library(ggrepel)
library(scales)
```

```{r}
rawdf = read.csv("bench_report_2026Aug10.csv") %>%
  filter(!str_detect(Tool, "-c50000")) %>%
  mutate(
    threads = if_else(
      str_detect(Tool, "thread"), gsub(".* ([0-9]{1,2}) thread.*", "\\1", Tool), "1"),
    Tool = if_else(
      str_detect(Tool, "thread"), gsub("(.*).* [0-9]{1,2} thread.*", "\\1", Tool), Tool),
    Mode = str_replace_all(Mode, "plp", ""), 
    
    Tool = if_else(
      str_detect(Mode, "histo"), 
      paste(Tool, Mode),
      Tool,
    ),
    
    Tool = str_replace_all(Tool, "pileuphi", "pileup-hi"),
    Tool = str_replace_all(Tool, "para_mpileup", "parallel samtools mpileup"),
    
    File = case_when(
      str_detect(File, "_") ~ str_split_i(File, "_", 1),
      str_detect(File, "\\.") ~ str_split_i(File, "\\.", 1),
      .default = File
    ),
    Sample = case_when(
      str_detect(File, "ERR2756166") ~ "T. pallidum 1",
      str_detect(File, "ERR2756169") ~ "T. pallidum WGS - HiSeq 2500",
      str_detect(File, "SRR19895870") ~ "Rocoto pepper - NovaSeq 6000",
      str_detect(File, "SRR36374445") ~ "Human WGS - Ultima",
      str_detect(File, "SRR30646148") ~ "Human WGS - Onso",
      str_detect(File, "SRR30646149") ~ "Human WGS - Revio",
      str_detect(File, "SRR30646150") ~ "Human WGS - Revio 2",
      str_detect(File, "DRR793869") ~ "Human WGS - NovaSeq X Plus"
    )
    )

rawdf <- rawdf %>%
  mutate(
    Tool = factor(Tool, levels = c("samtools mpileup", "parallel samtools mpileup", "sambamba mpileup", "bam_readcount", "perbase base-depth", "pileup-hi", "pileup-hi histo")),
    Sample = factor(Sample, levels = c("Human WGS - NovaSeq X Plus",  "Human WGS - Ultima", "Human WGS - Revio", "Rocoto pepper - NovaSeq 6000", "T. pallidum WGS - HiSeq 2500")),
    threads = factor(threads, levels = c("1", "4", "8", "12")),
  ) %>%
  filter(!File %in% c("ERR2756166", "SRR30646148", "SRR30646150")) %>%
  filter(!(Tool == "parallel samtools mpileup" & threads == "1")) %>%
  arrange(Tool, threads)
# 
rawdf_sum <- rawdf %>%
  filter(Status != "Terminated") %>%
  group_by(File, Sample, Tool, threads) %>%
  summarize(
    mean_runtime = mean(Runtime), median_runtime = median(Runtime), sd_runtime = sd(Runtime),
    mean_mem = mean(Peak.memory.used), median_mem = median(Peak.memory.used), sd_mem = sd(Peak.memory.used),
    ) %>%
  arrange(Tool, threads)
```
```{r}

metrics = read.csv("alignment_metrics_table.csv") %>%
  mutate(File = str_split_i(File, "_", 1)) %>%
  mutate(File = str_replace_all(File, ".bam", ""))
```

```{r}
FILL_SCALE = scale_fill_manual(values = c(
  "samtools mpileup" = "goldenrod3",
  # "perbase base-depth" = "plum4", 
  "perbase base-depth" = "plum4",
  # "pileup-hi plp" = "indianred4",
  "pileup-hi" = "indianred4",
  "pileup-hi histo" = "indianred2",
  "parallel samtools mpileup" = "goldenrod4",
  "sambamba mpileup" = "#458B74",
  "bam_readcount" = "#00688B"
  ))

COLOR_SCALE = scale_color_manual(values = c(
  "samtools mpileup" = "goldenrod3",
  # "perbase base-depth" = "plum4", 
  "perbase base-depth" = "plum4",
  "pileup-hi" = "indianred4",
  "pileup-hi histo" = "indianred2",
  "parallel samtools mpileup" = "goldenrod4",
  "sambamba mpileup" = "#458B74",
  "bam_readcount" = "#00688B"
  
  ))

AXIS_TEXT_COLOR = adjustcolor("black", alpha.f = 0.82)
```

```{r}
label_df <- rawdf_sum %>%
  distinct(Sample, File) %>%
  left_join(metrics, by = "File") %>%
  mutate(
    depth_label = paste0("mean depth: ", round(MeanDepth, 1)),
    cov_label   = paste0("mean coverage: ", round(Coverage, 1), "%")
  )

runtime = rawdf_sum %>%
  ggplot(aes(x = threads, y = mean_runtime, fill = Tool)) +
  facet_grid(~Sample, scales = "free", space = "free_x") + 
  geom_col(position = position_dodge(preserve = "single"), color = "black") +
  geom_errorbar(aes(x = threads, ymin = mean_runtime - sd_runtime, ymax = mean_runtime + sd_runtime),
                position = position_dodge(preserve = "single")) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 20000)) +
  FILL_SCALE +
  theme_classic() +
  xlab("Threads") +
  ylab("Runtime (seconds)") +
  geom_text(
    data = label_df,
    aes(label = depth_label),
    y = 19300,
    # x = 0.55,
    x = 2.5,
    inherit.aes = FALSE,
    check_overlap = TRUE,
    halign = 0.5,
    hjust = 0.5,
    size = 6 * 5/14
  ) +
  geom_text(
    data = label_df,
    aes(label = cov_label),
    y = 18500,
    # x = 0.55,
    x = 2.5,
    inherit.aes = FALSE,
    check_overlap = TRUE,
    halign = 0.5,
    hjust = 0.5,
    size = 6 * 5/14
  ) +
  guides(fill = guide_legend(label.position = "left")) +
  theme(
    legend.position = c(0.90, 0.57),
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    text = element_text(size = 8),
    panel.background = element_blank(),
    plot.background = element_blank(),
    legend.key.size = unit(0.45, "cm"),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10),
    axis.text.x = element_text(size = 8, color = AXIS_TEXT_COLOR),
    axis.text.y = element_text(size = 8, color = AXIS_TEXT_COLOR)
  )
runtime
# ggsave("runtime.pdf", runtime, width = 8, height = 5, dpi = 600)
```

```{r}
memory = rawdf_sum %>%
  ggplot(aes(x = threads, y = mean_mem, fill = Tool)) + 
  facet_grid(~Sample, scales = "free", space = "free_x") +
  geom_col(position = position_dodge(preserve = "single"), color = "black") +
  geom_errorbar(aes(x = threads, ymin = mean_mem - sd_mem, ymax = mean_mem + sd_mem), position = position_dodge(preserve = "single"), color = "black") +
  scale_x_discrete(position = "top") +
  FILL_SCALE +
  scale_y_reverse(expand = c(0, 0), limits = c(0, 20)) +
  theme_classic() + 
  ylab("Peak memory\nusage (GB)") + 
  xlab("Threads") +
  theme(
    strip.text = element_blank(),
    strip.background = element_blank(),
    legend.position = "none",
    text = element_text(size = 8),
    panel.background = element_blank(),
    plot.background = element_blank(),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10),
    axis.text.x = element_text(size = 8, color = AXIS_TEXT_COLOR),
    axis.text.y = element_text(size = 8,color = AXIS_TEXT_COLOR)
    )

memory

ggsave("memory.pdf", memory, width = 8, height = 5, dpi = 600)
```

# now plot output size comparison
```{r}
# sizedf = read.csv("size_comp_02_04_2026_11_22_29.csv") %>%
sizedf = read.csv("size_comp_2026Mar31.csv") %>%
  mutate(
    Tool = paste0("pileup-hi ", Mode),
    Mode = str_replace_all(Mode, "plp", "pileup"),
    Sample = case_when(
      str_detect(File, "ERR2756166") ~ "T. pallidum 1",
      str_detect(File, "ERR2756169") ~ "T. pallidum WGS - HiSeq 2500",
      str_detect(File, "SRR19895870") ~ "Rocoto pepper - NovaSeq 6000",
      str_detect(File, "SRR36374445") ~ "Human WGS - Ultima",
      str_detect(File, "SRR30646148") ~ "Human WGS - Onso",
      str_detect(File, "SRR30646149") ~ "Human WGS - Revio",
      str_detect(File, "SRR30646150") ~ "Human WGS - Revio 2",
      str_detect(File, "DRR793869") ~ "Human WGS - NovaSeq X Plus"
    )
    ) %>% 
  group_by(Sample) %>%
  mutate(change = max(Size) - min(Size), perc = Size / max(Size) * 100, perc_saved = change / max(Size)) %>%
  # filter(!File %in% c("ERR2756166.bam", "SRR30646148.bam", "SRR30646150_hg38.bam")) %>%
  filter(!str_detect(File, "ERR2756166|SRR30646148|SRR30646150")) %>%
  ungroup()

# depth, cov, genome length
# metrics = read.csv("aln_metrics.txt", sep = "\t") %>%
#   filter(Ref != "chrM") %>%
#   group_by(File) %>%
#   # collapse all chrs to single file
#   summarize(mean_depth = mean(MeanDepth), coverage = mean(Coverage), length = sum(Length))
# 
# sizedf = sizedf %>% left_join(metrics, by = "File", relationship = "many-to-one") %>% mutate(depthlen = mean_depth / length)
```

```{r fig.width = 8, fig.height = 2, dpi = 800}
sizedf$Mode = factor(sizedf$Mode, levels = c("pileup", "histo"))

size = sizedf %>%
  mutate(Sample = str_replace(Sample, " - ", "\n"),
         Sample = str_replace(Sample, " ", "\n"),
         Mode = str_replace(Mode, "histo", "histo\n(abbreviated)")
         ) %>%
  mutate(
    Sample = factor(Sample, levels = c("Human\nWGS\nNovaSeq X Plus",  "Human\nWGS\nUltima", "Human\nWGS\nRevio", "Rocoto\npepper\nNovaSeq 6000", "T.\npallidum WGS\nHiSeq 2500")),
  ) %>%
  ggplot() +
  facet_grid(~Sample) +
  geom_line(aes(x = Mode, y = perc, group = 1), linetype = "dashed", color = "grey") +
  geom_point(aes(x = Mode, y = perc, color = Mode), size = 2.3, alpha = 0.8) + 
  scale_color_manual(values = c("pileup" = "indianred4", "histo\n(abbreviated)" = "indianred2")) +
  geom_text_repel(aes(x = Mode, y = perc, label = paste0(signif(Size, 3), " GB")), min.segment.length = 1000, size = 7 * 5/14, seed = 1) +
  scale_y_continuous(limits = c(0, 100)) +
  theme_classic() +
  ylab("% reduction in\noutput size") + 
  xlab("") + 
  theme(
    legend.position = "none",
    text = element_text(size = 8),
    strip.text = element_blank(),
    strip.background = element_blank(),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10),
    axis.text.x = element_text(size = 8, color = AXIS_TEXT_COLOR),
    axis.text.y = element_text(size = 8, color = AXIS_TEXT_COLOR),
    )
  

size
ggsave("size.pdf", size, width = 8, height = 2, dpi = 1000)
```
# put it all together
```{r fig.height = 6.2, width = 8.2, dpi = 800}
runtime_mem = ((runtime  + theme(axis.text.x = element_blank(), axis.title.x = element_blank())) / plot_spacer() / memory / plot_spacer() / size) + plot_layout(axes = "collect", axis_titles = "collect", heights = c(0.46, -0.05, 0.36, 0.01, 0.18))

runtime_mem[[1]] <- runtime_mem[[1]] + theme(plot.margin = margin(t = 0, r = 5.5, b = 5.5, l = 5.5))  # kill top padding
runtime_mem[[5]] <- runtime_mem[[5]] + theme(plot.margin = margin(t = 5.5, r = 5.5, b = 0, l = 5.5))  # kill bottom padding

runtime_mem
ggsave("figures/figure1C_2026Apr08.pdf", runtime_mem, dpi = 1000, width = 8.2, height = 6.2)
```

# plot hashes of plp output with a correlation plot
```{r}

hashdf = read.csv("hashes_2026Aug10.csv") %>%
  filter(!str_detect(File, "ERR2756166|SRR30646150|SRR30646148")) %>%
  filter(!str_detect(Tool, "sambamba")) %>%
  mutate(
    Sample = case_when(
      str_detect(File, "ERR2756166") ~ "T. pallidum 1",
      str_detect(File, "ERR2756169") ~ "T. pallidum WGS - HiSeq 2500",
      str_detect(File, "SRR19895870") ~ "Rocoto pepper - NovaSeq 6000",
      str_detect(File, "SRR36374445") ~ "Human WGS - Ultima",
      str_detect(File, "SRR30646148") ~ "Human WGS - Onso",
      str_detect(File, "SRR30646149") ~ "Human WGS - Revio",
      str_detect(File, "SRR30646150") ~ "Human WGS - Revio 2",
      str_detect(File, "DRR793869") ~ "Human WGS - NovaSeq X Plus"
    )
  ) %>%
  mutate(
    Sample = factor(Sample, levels = c("Human WGS - NovaSeq X Plus",  "Human WGS - Ultima", "Human WGS - Revio", "Rocoto pepper - NovaSeq 6000", "T. pallidum WGS - HiSeq 2500")),
  ) %>%
  arrange(Sample) %>%
  mutate(
    Hash = str_split_i(Hash, "\\s+", 1),
    # Hash_numeric = as.integer(factor(Hash, levels = unique(Hash))),
    
    Hash_numeric = sapply(Hash, function(h) {
      as.numeric(paste0("0x", substr(digest(h, algo = "crc32"), 1, 8)))
    }),
    Threads = if_else(str_detect(Tool, "threads"), as.numeric(gsub(".* ([0-9]+) thread.*", "\\1", Tool)), 1),
    Tool = if_else(str_detect(Tool, "threads"), str_split_i(Tool, " ", 1), Tool),
  )

pileuphi_data <- hashdf %>%
  filter(Tool == "pileuphi") %>%
  select(Sample, hash_pileuphi = Hash_numeric, Threads)

samtools_data <- hashdf %>%
  filter(Tool == "samtools mpileup") %>%
  select(Sample, hash_samtools = Hash_numeric)

plot_data <- samtools_data %>%
  inner_join(pileuphi_data, by = "Sample") %>%
  mutate(
      hashes_match = (hash_samtools == hash_pileuphi),
      match_label = if_else(hashes_match, "Match", "Mismatch"),
      hash_wrapped = gsub("(.{16})", "\\1\n", hash_pileuphi)
    )
```


```{r fig.width = 3.4, fig.height = 3.4, dpi = 800}
cor_value <- cor(plot_data$hash_samtools, plot_data$hash_pileuphi, method = "pearson")

SAMPLE_COLORS = c(
  "Rocoto pepper - NovaSeq 6000" = "tan3",
  "Human WGS - Ultima" = "paleturquoise4",
  "Human WGS - Onso" = "darkseagreen4",
  "Human WGS - Revio" = "slateblue4",
  "Human WGS - Revio 2" = "slateblue1",
  "T. pallidum WGS - HiSeq 2500" = "lightpink4",
  "Human WGS - NovaSeq X Plus" = "darkseagreen4"

)

label_data <- plot_data %>%
  group_by(Sample) %>%
  summarize(
    x = mean(hash_samtools),
    y = mean(hash_pileuphi)
  )

# scientific_label <- function(x) {
#   if (str_equal(x, "1e8")) {
#     return ("0")
#   }
#   parse(text = gsub("e\\+?(-?)0*(\\d+)", "\\1%*%10^\\2", scales::scientific(x)))
# }

scientific_label <- function(x) {
  labels <- gsub("e\\+?(-?)0*(\\d+)", "\\1%*%10^\\2", scales::scientific(x))
  labels[x == 1e8] <- "0"
  parse(text = labels)
}

cor = plot_data %>%
  ggplot(aes(x = hash_samtools, y = hash_pileuphi)) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed",
              color = "black", linewidth = 0.8) +
  geom_jitter(aes(color = Sample, size = factor(Threads)), alpha = 1,
                width = max(plot_data$hash_samtools) * 0,
                height = max(plot_data$hash_pileuphi) * 0,
              shape = 1
              ) +
  geom_text_repel(
    data = label_data,
    # aes(x = x / min_hash_to_normalize, y = y / min_hash_to_normalize, label = Sample, color = Sample),
    aes(x = x, y = y, label = Sample, color = Sample),
    direction = "x",
    xlim = c(1e8, 1e10),
    size = 7 * 5/14,
    segment.color = "black",
    nudge_x = case_when(
      label_data$Sample == "Human WGS - NovaSeq X Plus" ~ 1.55e9,
      label_data$Sample == "Rocoto pepper - NovaSeq 6000" ~ 1.57e9,
      label_data$Sample == "Human WGS - Revio" ~ -1.11e9,
      label_data$Sample == "Human WGS - Ultima" ~ -1.13e9,
      label_data$Sample == "T. pallidum WGS - HiSeq 2500" ~ -1.51e9,
      .default = 0,
    ),
    nudge_y = if_else(
      label_data$y < 2e9,
      # 0.2e9,
      0,
      0
    ),
    seed = 1,
    max.overlaps = 20,
    box.padding = 0.15,
    fontface = "bold",
    min.segment.length = 100) +

    annotate("text", x = 1.3e9, y = 1.3e9 + 0.25e9, angle = 45, label = "y = x") +

    annotate("text", x = Inf, y = -Inf,
             label = paste0("Pearson r = ", signif(cor_value, 2)),
             hjust = 1, vjust = -0.5, size = 7 * 5/14,
             fontface = "bold",
             ) +

    scale_size_manual(values = c("1" = 1, "4" = 2, "8" = 4, "12" = 6), name = "Threads") +
    scale_color_manual(values = SAMPLE_COLORS) +
    guides(color = "none") +

    scale_x_continuous(labels = scientific_label, breaks = c(1e8, 1e9, 2e9, 3e9, 4e9, 5e9), limits = c(1e8, 5e9), expand = c(0, 0)) +
    scale_y_continuous(labels = scientific_label, breaks = c(1e8, 1e9, 2e9, 3e9, 4e9, 5e9), limits = c(1e8, 5e9), expand = c(0, 0)) +

    theme_classic() +
    theme(
      legend.position = c(0.12, 0.85),
      text = element_text(size = 8),
      axis.title.x = element_text(size = 10),
      axis.title.y = element_text(size = 10),
      legend.key.spacing.y = unit(1, "pt"),
      legend.key.size = unit(10, "pt"),

      axis.text.x = element_text(size = 8, color = AXIS_TEXT_COLOR),
      axis.text.y = element_text(size = 8, color = AXIS_TEXT_COLOR),
      ) +
    xlab("Output nhash (samtools mpileup)") +
    ylab("Output nhash (pileup-hi)") +
    coord_fixed(ratio = 1)

cor
ggsave("figures/cor.pdf", cor, width = 3.4, height = 3.4, dpi = 800)
```

```{r}
comp = rawdf_sum %>% 
  # mutate(Tool = str_replace_all(Tool, "parallel samtools mpileup", "samtools mpileup")) %>%
  filter(Tool != "pileup-hi histo") %>%
  group_by(File, threads) %>%
  summarize(
    runtime_diff_mpileup = mean(mean_runtime[Tool == "samtools mpileup"]) / mean(mean_runtime[Tool == "pileup-hi"]),
    memory_diff_mpileup = mean(mean_mem[Tool == "samtools mpileup"]) / mean(mean_mem[Tool == "pileup-hi"]),
    
    runtime_diff_perbase = mean(mean_runtime[Tool == "perbase base-depth"]) / mean(mean_runtime[Tool == "pileup-hi"]),
    memory_diff_perbase = mean(mean_mem[Tool == "perbase base-depth"]) / mean(mean_mem[Tool == "pileup-hi"]),
    
    runtime_diff_para = mean(mean_runtime[Tool == "parallel samtools mpileup"]) / mean(mean_runtime[Tool == "pileup-hi"]),
    memory_diff_para = mean(mean_mem[Tool == "parallel samtools mpileup"]) / mean(mean_mem[Tool == "pileup-hi"]),
    
    memory_diff_para_gb = mean(mean_mem[Tool == "parallel samtools mpileup"]) - mean(mean_mem[Tool == "pileup-hi"]),
    )

comp_single_thread = rawdf_sum %>%
  filter(Tool == "samtools mpileup" | (Tool == "pileup-hi" & threads == 12)) %>%
  group_by(File) %>%
  summarize(
    runtime_diff_mpileup_1t = mean(mean_runtime[Tool == "samtools mpileup"]) / max(mean_runtime[Tool == "pileup-hi"])
  )

mean_pileuphi_mem = mean(rawdf_sum$mean_mem[rawdf_sum$Tool == "pileup-hi"])
mean_perbase_mem = mean(rawdf_sum$mean_mem[rawdf_sum$Tool == "perbase base-depth"])

```

# Per-file summary statistics
```{r}
per_file_table = rawdf_sum %>%
  filter(Tool != "pileup-hi histo") %>%
  select(File, Sample, Tool, threads, Runtime_s = mean_runtime, Memory_GB = mean_mem) %>%
  mutate(
    threads = as.character(threads),
    Tool = factor(Tool, levels = c("samtools mpileup", "parallel samtools mpileup", "sambamba mpileup", "perbase base-depth", "bam_readcount", "pileup-hi"))
  ) %>%
  pivot_wider(
    names_from = Tool,
    values_from = c(Runtime_s, Memory_GB),
    names_glue = "{Tool}: {.value}"
  )

knitr::kable(
  per_file_table %>%
    select(File, Sample, threads, ends_with("Runtime_s")),
  digits = 1,
  format = "pipe"
)

knitr::kable(
  per_file_table %>%
    select(File, Sample, threads, ends_with("Memory_GB")),
  digits = 2,
  format = "pipe"
)
```

```{r}
best_thread_table = rawdf_sum %>%
  filter(Tool != "pileup-hi histo") %>%
  select(File, Sample, Tool, threads, mean_runtime, mean_mem) %>%
  group_by(File, Tool) %>%
  slice_max(as.numeric(as.character(threads)), n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  group_by(File) %>%
  mutate(
    runtime_fold = mean_runtime / mean_runtime[Tool == "pileup-hi"],
    memory_fold = mean_mem / mean_mem[Tool == "pileup-hi"]
  ) %>%
  ungroup() %>%
  filter(Tool != "pileup-hi") %>%
  arrange(File, Tool)

knitr::kable(best_thread_table, digits = 3, format = "pipe", col.names = c("File", "Sample", "Tool", "Threads", "Runtime_s", "Memory_GB", "Runtime_x_pileup-hi", "Memory_x_pileup-hi"))
```

```{r}
pileuphi_improvement = function(tool) {
  best_thread_table %>%
    filter(Tool == tool) %>%
    mutate(
      cpu = if_else(
        runtime_fold > 1,
        paste0("ran ", sprintf("%.1f", runtime_fold), "x faster"),
        paste0("ran ", sprintf("%.1f", 1 / runtime_fold), "x slower")
      ),
      mem = if_else(
        memory_fold > 1,
        paste0("used ", sprintf("%.1f", memory_fold), "x less peak memory"),
        paste0("used ", sprintf("%.1f", 1 / memory_fold), "x more peak memory")
      ),
      sentence = paste0(
        "On ", Sample, " (", File, "), pileup-hi (12 threads) ", cpu, " and ",
        mem, " than ", tool, " (", threads, " threads)"
      )
    ) %>%
    pull(sentence)
}

max_improvement = function(tool) {
  d = best_thread_table %>% filter(Tool == tool)
  d = d %>% mutate(mem_fav = pmax(memory_fold, 1 / memory_fold),
                   mem_dir = if_else(memory_fold > 1, "less", "more"))
  rt_best = d %>% slice_max(runtime_fold, n = 1)
  mem_best = d %>% slice_max(mem_fav, n = 1)
  paste0(
    "vs ", tool, ": up to ", sprintf("%.1f", rt_best$runtime_fold), "x ",
    if_else(rt_best$runtime_fold > 1, "faster", "slower"),
    " (", rt_best$Sample, "), up to ",
    sprintf("%.1f", mem_best$mem_fav), "x ", mem_best$mem_dir,
    " peak memory (", mem_best$Sample, ")"
  )
}

comparable_tools = setdiff(as.character(unique(best_thread_table$Tool)), "bam_readcount")
```

```{r}
for (t in comparable_tools) {
  cat("\n-- vs ", t, " --\n", sep = "")
  cat(pileuphi_improvement(t), sep = "\n")
}
cat("\n-- max improvements --\n")
cat(vapply(comparable_tools, max_improvement, character(1)), sep = "\n")
```

```{r}
knitr::kable(
  sizedf %>%
    mutate(`Size (GB)` = signif(Size, 3), `Output size reduction (%)` = round(100 - perc, 1)) %>%
    select(File, Sample, Mode, `Size (GB)`, `Output size reduction (%)`),
  digits = 2,
  format = "pipe"
)
```
